version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: teklif_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: teklif_service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .env:/app/.env

  migrate:
    image: migrate/migrate
    container_name: teklif_migrate
    volumes:
      - ../db:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}", "up" ]